export const uploadImageFileList = [
  { name: 'android_layerpopup_image', maxCount: 1 },
  { name: 'android_lnbtoptext_image', maxCount: 1 },
  { name: 'android_lnbtopbutton_image', maxCount: 1 },
  { name: 'android_homeband_image', maxCount: 1 },
  { name: 'android_voucher_index_image', maxCount: 1 },
  { name: 'ios_layerpopup_image', maxCount: 1 },
  { name: 'ios_lnbtoptext_image', maxCount: 1 },
  { name: 'ios_lnbtopbutton_image', maxCount: 1 },
  { name: 'ios_homeband_image', maxCount: 1 },
  { name: 'ios_voucher_index_image', maxCount: 1 },
  { name: 'pc_layerpopup_image', maxCount: 1 },
  { name: 'pc_lnbtoptext_image', maxCount: 1 },
  { name: 'pc_lnbtopbutton_image', maxCount: 1 },
  { name: 'pc_homeband_image', maxCount: 1 },
  { name: 'pc_voucher_index_image', maxCount: 1 },
  { name: 'mobile_layerpopup_image', maxCount: 1 },
  { name: 'mobile_lnbtoptext_image', maxCount: 1 },
  { name: 'mobile_lnbtopbutton_image', maxCount: 1 },
  { name: 'mobile_homeband_image', maxCount: 1 },
  { name: 'mobile_voucher_index_image', maxCount: 1 },
  //add
  { name: 'android_floating_banner_icon', maxCount: 1 },
  { name: 'ios_floating_banner_icon', maxCount: 1 },
  { name: 'mobile_floating_banner_icon', maxCount: 1 },
  { name: 'pc_floating_banner_icon', maxCount: 1 },
];